//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myvas.AspNetCore.Weixin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Myvas.AspNetCore.Weixin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimistic concurrency failure, object has been modified..
        /// </summary>
        internal static string ConcurrencyFailure {
            get {
                return ResourceManager.GetString("ConcurrencyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown failure has occurred..
        /// </summary>
        internal static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname &apos;{0}&apos; is already subscribed..
        /// </summary>
        internal static string DuplicatedNickname {
            get {
                return ResourceManager.GetString("DuplicatedNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenId &apos;{0}&apos; is already subscribed..
        /// </summary>
        internal static string DuplicateOpenId {
            get {
                return ResourceManager.GetString("DuplicateOpenId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnionId &apos;{0}&apos; is already subscribed..
        /// </summary>
        internal static string DuplicateUnionId {
            get {
                return ResourceManager.GetString("DuplicateUnionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IQueryableSubscriberStore&lt;TSubscriber&gt;..
        /// </summary>
        internal static string StoreNotIQueryableSubscriberStore {
            get {
                return ResourceManager.GetString("StoreNotIQueryableSubscriberStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement ISubscriberStore&lt;TSubscriber&gt;..
        /// </summary>
        internal static string StoreNotISubscriberStore {
            get {
                return ResourceManager.GetString("StoreNotISubscriberStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user associated with this Weixin subscriber already exists..
        /// </summary>
        internal static string SubscriberAlreadyAssociated {
            get {
                return ResourceManager.GetString("SubscriberAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber is locked out..
        /// </summary>
        internal static string SubscriberLockedOut {
            get {
                return ResourceManager.GetString("SubscriberLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber &apos;{0}&apos; had unsubscribed..
        /// </summary>
        internal static string SubscriberUnsubscribed {
            get {
                return ResourceManager.GetString("SubscriberUnsubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is locked out..
        /// </summary>
        internal static string UserLockedOut {
            get {
                return ResourceManager.GetString("UserLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; is not a subscriber..
        /// </summary>
        internal static string UserNotSubscriber {
            get {
                return ResourceManager.GetString("UserNotSubscriber", resourceCulture);
            }
        }
    }
}
