// <auto-generated />
using System;
using Demo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Demo.Migrations.WeixinDb
{
    [DbContext(typeof(WeixinDbContext))]
    partial class WeixinDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085");

            modelBuilder.Entity("Demo.Models.ReceivedTextMessage", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("From");

                    b.Property<DateTimeOffset>("ReceivedTime");

                    b.Property<string>("To");

                    b.HasKey("Id");

                    b.ToTable("ReceivedTextMessages");
                });

            modelBuilder.Entity("Demo.Models.WeixinSubscriber", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AvatorImage");

                    b.Property<string>("Gender");

                    b.Property<string>("NickName");

                    b.Property<string>("OpenId");

                    b.HasKey("Id");

                    b.ToTable("Subscribers");
                });
#pragma warning restore 612, 618
        }
    }
}
