// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace WeixinSiteSample.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("Myvas.AspNetCore.Weixin.Models.AuditEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditEntires");
                });

            modelBuilder.Entity("Myvas.AspNetCore.Weixin.Models.EventReceivedEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreateTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromUserName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("MsgType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToUserName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WeixinReceivedEvents", (string)null);

                    b.HasDiscriminator<string>("Event").HasValue("EventReceivedEntry");
                });

            modelBuilder.Entity("Myvas.AspNetCore.Weixin.Models.MessageReceivedEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreateTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromUserName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("MsgId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MsgType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToUserName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WeixinReceivedMessages", (string)null);

                    b.HasDiscriminator<string>("MsgType").HasValue("MessageReceivedEntry");
                });

            modelBuilder.Entity("WeixinSiteSample.Data.ApplicationUser", b =>
                {
                    b.Property<string>("OpenId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatorImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("MentorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("SubscribedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnionId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Unsubscribed")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UnsubscribedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("OpenId");

                    b.ToTable("WeixinSubscribers", (string)null);
                });

            modelBuilder.Entity("Myvas.AspNetCore.Weixin.Models.ClickMenuEventReceivedEntry", b =>
                {
                    b.HasBaseType("Myvas.AspNetCore.Weixin.Models.EventReceivedEntry");

                    b.Property<string>("EventKey")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("EventKey");

                    b.HasDiscriminator().HasValue("CLICK");
                });

            modelBuilder.Entity("Myvas.AspNetCore.Weixin.Models.ImageMessageReceivedEntry", b =>
                {
                    b.HasBaseType("Myvas.AspNetCore.Weixin.Models.MessageReceivedEntry");

                    b.Property<string>("MediaId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("MediaId");

                    b.Property<string>("PicUrl")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("image");
                });

            modelBuilder.Entity("Myvas.AspNetCore.Weixin.Models.LinkMessageReceivedEntry", b =>
                {
                    b.HasBaseType("Myvas.AspNetCore.Weixin.Models.MessageReceivedEntry");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("link");
                });

            modelBuilder.Entity("Myvas.AspNetCore.Weixin.Models.LocationEventReceivedEntry", b =>
                {
                    b.HasBaseType("Myvas.AspNetCore.Weixin.Models.EventReceivedEntry");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precision")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("LOCATION");
                });

            modelBuilder.Entity("Myvas.AspNetCore.Weixin.Models.LocationMessageReceivedEntry", b =>
                {
                    b.HasBaseType("Myvas.AspNetCore.Weixin.Models.MessageReceivedEntry");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Scale")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("location");
                });

            modelBuilder.Entity("Myvas.AspNetCore.Weixin.Models.QrscanEventReceivedEntry", b =>
                {
                    b.HasBaseType("Myvas.AspNetCore.Weixin.Models.EventReceivedEntry");

                    b.Property<string>("EventKey")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("EventKey");

                    b.Property<string>("Ticket")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("Ticket");

                    b.HasDiscriminator().HasValue("SCAN");
                });

            modelBuilder.Entity("Myvas.AspNetCore.Weixin.Models.ShortVideoMessageReceivedEntry", b =>
                {
                    b.HasBaseType("Myvas.AspNetCore.Weixin.Models.MessageReceivedEntry");

                    b.Property<string>("MediaId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("MediaId");

                    b.Property<string>("ThumbMediaId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("ThumbMediaId");

                    b.HasDiscriminator().HasValue("shortvideo");
                });

            modelBuilder.Entity("Myvas.AspNetCore.Weixin.Models.SubscribeEventReceivedEntry", b =>
                {
                    b.HasBaseType("Myvas.AspNetCore.Weixin.Models.EventReceivedEntry");

                    b.Property<string>("EventKey")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("EventKey");

                    b.Property<string>("Ticket")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("Ticket");

                    b.HasDiscriminator().HasValue("subscribe");
                });

            modelBuilder.Entity("Myvas.AspNetCore.Weixin.Models.TextMessageReceivedEntry", b =>
                {
                    b.HasBaseType("Myvas.AspNetCore.Weixin.Models.MessageReceivedEntry");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("text");
                });

            modelBuilder.Entity("Myvas.AspNetCore.Weixin.Models.UnsubscribeEventReceivedEntry", b =>
                {
                    b.HasBaseType("Myvas.AspNetCore.Weixin.Models.EventReceivedEntry");

                    b.HasDiscriminator().HasValue("unsubscribe");
                });

            modelBuilder.Entity("Myvas.AspNetCore.Weixin.Models.VideoMessageReceivedEntry", b =>
                {
                    b.HasBaseType("Myvas.AspNetCore.Weixin.Models.MessageReceivedEntry");

                    b.Property<string>("MediaId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("MediaId");

                    b.Property<string>("ThumbMediaId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("ThumbMediaId");

                    b.HasDiscriminator().HasValue("video");
                });

            modelBuilder.Entity("Myvas.AspNetCore.Weixin.Models.ViewMenuEventReceivedEntry", b =>
                {
                    b.HasBaseType("Myvas.AspNetCore.Weixin.Models.EventReceivedEntry");

                    b.Property<string>("EventKey")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("EventKey");

                    b.HasDiscriminator().HasValue("VIEW");
                });

            modelBuilder.Entity("Myvas.AspNetCore.Weixin.Models.VoiceMessageReceivedEntry", b =>
                {
                    b.HasBaseType("Myvas.AspNetCore.Weixin.Models.MessageReceivedEntry");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("MediaId");

                    b.Property<string>("Recognition")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("voice");
                });
#pragma warning restore 612, 618
        }
    }
}
