# This workflow will publish NuGet packages to nuget.org
# For more information see: https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/about-packaging-with-github-actions

name: publish

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  build-and-test:
    strategy:
      matrix:
        dotnet:
          - version: '3.1.x'
            framework: 'netcoreapp3.1'
        configuration:
          - Release
    uses: ./.github/workflows/build-and-test.yml
    with:
      dotnet-version: ${{ matrix.dotnet.version }}
      dotnet-framework: ${{ matrix.dotnet.framework }}
      configuration: ${{ matrix.configuration }}
  
  pack-and-publish:
    needs: [ 'build-and-test' ]
    uses: ./.github/workflows/pack-and-publish.yml
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
