# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: test
permissions:
  contents: read
  pull-requests: write
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - "*.md"
      - ".github/**"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "*.md"
      - ".github/**"
           
jobs:
  setup-redis:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Output redis host
        run: |
          hostname
          echo "redis_host=$(hostname)" >> $GITHUB_ENV
          echo "$(hostname)" > redis_host.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: redis_host
          path: redis_host.txt
          overwrite: true
      - name: Check out repository code
        uses: actions/checkout@v4        
      - name: Install redis-cli
        id: set-env
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-tools
      - name: keepalive
        run: |
          #!/bin/bash
          ping ${redis_host} -c 1
          redis-cli ping
          MAX_ATTEMPTS=120
          redis-cli set redis-server-alive-counter 0
          while [ $(redis-cli get redis-server-alive-counter) -lt $MAX_ATTEMPTS ]; do
              echo "redis-server ${redis_host} is listening..."
              sleep 1
              redis-cli incr redis-server-alive-counter
          done
          if [ $(redis-cli get redis-server-alive-counter) -ge $MAX_ATTEMPTS ]; then
              exit 1
          else
              exit 0
          fi

  wait-for-redis-server:
    runs-on: ubuntu-latest
    outputs:
      redis_host: ${{ steps.set-env.outputs.redis_host }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install redis-cli
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-tools
      - name: Wait 10 seconds for upload artifact
        run: sleep 10
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: redis_host
      - name: Use the artifact
        id: set-env
        run: |
          hostname
          cat redis_host.txt
          echo "redis_host=$(cat redis_host.txt)" >> $GITHUB_ENV
      - name: Wait for redis-server ready
        run: |
          ping ${redis_host} -c 1
          WAIT_FOR_REDIS_SERVER_COUNTER=0
          while true; do
            if redis-cli -h ${redis_host} ping &> /dev/null; then
              echo "redis-server ${redis_host} is running."
              redis-cli -h ${redis_host} set redis-server-alive-counter 0
              exit 0
              break
            else
              echo "Attempt $WAIT_FOR_REDIS_SERVER_COUNTER: redis-server ${redis_host} is not responding. Retrying in 1 second..."
              WAIT_FOR_REDIS_SERVER_COUNTER=$((WAIT_FOR_REDIS_SERVER_COUNTER+1))
              sleep 1            
              if [ "$WAIT_FOR_REDIS_SERVER_COUNTER" -gt 60 ]; then
                echo "WAIT_FOR_REDIS_SERVER_COUNTER exceeded 60. Breaking the loop."
                exit 1
                break
              fi
            fi
          done
          exit 1

  build-and-test:
    needs: [wait-for-redis-server]
    if: ${{ success() }}
    strategy:
      matrix:
        dotnet:
          - version: '3.1.x'
            framework: 'netcoreapp3.1'
          - version: '5.0.x'
            framework: 'net5.0'
          - version: '6.0.x'
            framework: 'net6.0'
          - version: '7.0.x'
            framework: 'net7.0'
          - version: '8.0.x'
            framework: 'net8.0'
          - version: '9.0.x'
            framework: 'net9.0'
        configuration: [ Debug, Release ]
    uses: ./.github/workflows/build-and-test.yml
    secrets:
      WEIXIN__APPID: ${{ secrets.WEIXIN__APPID }}
      WEIXIN__APPSECRET: ${{ secrets.WEIXIN__APPSECRET }}
    with:
      dotnet-version: ${{ matrix.dotnet.version }}
      dotnet-framework: ${{ matrix.dotnet.framework }}
      configuration: ${{ matrix.configuration }}
      redis_host: ${{ needs.wait-for-redis-server.outputs.redis_host }}
      redis_port: 6379

  shutdown-redis:
    runs-on: ubuntu-latest
    needs: [wait-for-redis-server, build-and-test]
    if: ${{ always() }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install redis-cli
        run: sudo apt-get install redis-tools
      - name: Keep alive
        run: |
          hostname
          redis-cli -h ${{ env.redis_host }} ping
          redis-cli -h ${{ env.redis_host }} set redis-server-alive-counter 9999
        env:
          redis_host: ${{ needs.wait-for-redis-server.outputs.redis_host }}

      