# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: test
permissions:
  contents: read
  pull-requests: write
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - "*.md"
      - ".github/**"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "*.md"
      - ".github/**"

jobs:
  setup-redis:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --name redis
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Test redis-cli
        run: redis-cli -h redis -p 6379 ping

  build-and-test:
    needs: setup-redis
    strategy:
      matrix:
        dotnet:
          - version: '3.1.x'
            framework: 'netcoreapp3.1'
          - version: '5.0.x'
            framework: 'net5.0'
          - version: '6.0.x'
            framework: 'net6.0'
          - version: '7.0.x'
            framework: 'net7.0'
          - version: '8.0.x'
            framework: 'net8.0'
          - version: '9.0.x'
            framework: 'net9.0'
        configuration: [ Debug, Release ]
    uses: ./.github/workflows/build-and-test.yml
    secrets:
      WEIXIN__APPID: ${{ secrets.WEIXIN__APPID }}
      WEIXIN__APPSECRET: ${{ secrets.WEIXIN__APPSECRET }}
    with:
      dotnet-version: ${{ matrix.dotnet.version }}
      dotnet-framework: ${{ matrix.dotnet.framework }}
      configuration: ${{ matrix.configuration }}
      redis_host: redis
      redis_port: 6379
      