# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: test
permissions:
  contents: read
  pull-requests: write
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - "*.md"
      - ".github/**"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "*.md"
      - ".github/**"
           
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    strategy:
      matrix:
        dotnet:
          - version: '3.1.x'
            framework: 'netcoreapp3.1'
          - version: '5.0.x'
            framework: 'net5.0'
          - version: '6.0.x'
            framework: 'net6.0'
          - version: '7.0.x'
            framework: 'net7.0'
          - version: '8.0.x'
            framework: 'net8.0'
          - version: '9.0.x'
            framework: 'net9.0'
        configuration: [ Debug, Release ]
      max-parallel: 1
    steps:
      - run: echo "The inputs.dotnet version is ${{ inputs.dotnet-version }}, framework is ${{ inputs.dotnet-framework }}."
      - run: echo "The inputs.configuration is ${{ inputs.configuration }}."
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install redis-server
        run: |
          sudo apt-get update
          sudo apt-get install redis-server -y
          sudo systemctl start redis-server
          sudo systemctl enable redis-server
          sudo systemctl status redis-server
      - name: Wait for redis-server
        uses: ./.github/workflows/build-and-test.yml
        with:
          dotnet-version: ${{ matrix.dotnet.version }}
          dotnet-framework: ${{ matrix.dotnet.framework }}
          configuration: ${{ matrix.configuration }}
          redis_host: localhost
          redis_port: 6379
        env:
          WEIXIN__APPID: ${{ secrets.WEIXIN__APPID }}
          WEIXIN__APPSECRET: ${{ secrets.WEIXIN__APPSECRET }}

